project:
  type: book
  output-dir: docs  # <--- This is important

book:
  title: "Handover Student Assistent"
  author: "Tim Roessling"
  chapters:
    - index.qmd
    - operational_tasks.qmd
    - dashboards.qmd
    - measures.qmd
    - tabular_editor.qmd
    - google_cloud_platforms.qmd
    - project_ideas.qmd
    - useful_links.qmd
    - hr.qmd
format:
  html:
    theme:
      - default
      - styles.scss
    css: styles.css


