---
title: "Google Cloud Platform (GCP)"
format: html
---

This section provides an overview of the Google Cloud Platform (GCP) tools we use for data management and analysis. GCP is essential for our data operations, enabling us to store, process, and analyze large datasets efficiently.

## Introduction to Google Cloud Platform (GCP)

Google Cloud Platform (GCP) is a suite of cloud computing services offered by Google. It provides a comprehensive set of tools for computing, storage, networking, big data, machine learning, and application development. GCP allows organizations to build, deploy, and scale applications and data solutions efficiently and securely.

### Key Functions of GCP

- **Compute**: Virtual machines, containers, and serverless computing for running applications and services.
- **Storage**: Scalable object storage, file storage, and databases for managing structured and unstructured data.
- **Networking**: Secure, high-performance networking solutions, including virtual private clouds and load balancing.
- **Big Data & Analytics**: Tools for data processing, analysis, and visualization, such as BigQuery and Dataflow.
- **Machine Learning & AI**: Pre-built and custom machine learning models, APIs, and infrastructure for AI workloads.
- **Security & Identity**: Comprehensive security, identity, and access management features to protect data and resources.

GCP's integrated services streamline workflows, improve collaboration, and support data-driven decision-making across the organization.

[BigQuery Tutorial (YouTube)](https://www.youtube.com/watch?v=MH5M2Crn6Ag&pp=ygURYmlncXVlcnkgdHV0b3JpYWzSBwkJvgkBhyohjO8%3D)

## How We Use GCP

We leverage GCP for:

- Storing and managing our data
- Data manipulation and transformation (using views)
- Automating data updates with scheduled queries
- Machine learning tasks and coding with Vertex AI
- Serverless computing tasks with Cloud Functions
- Data warehousing and analytics with BigQuery

## Your Main Activities in GCP

As part of your role, your primary activities in GCP include:

- Backfilling data as part of operational tasks
- Creating and managing scheduled queries to automate data updates
- Managing tables and views in BigQuery
- Using Vertex AI for machine learning tasks and coding
- Maintaining Cloud Functions for serverless computing tasks
