---
title: "HR"
format: html
---


This chapter provides essential information about HR processes at Pandora.

## Timesheet Submission

- **Monthly Timesheet:**  
    You are required to submit a monthly timesheet, logging your working hours for each day.
- **Pay Periods:**  
    Pay periods typically run from the 11th of one month to the 10th of the next month.  
    Ensure all hours are logged by the 10th of each month.
- **Approval:**  
    Kasper will review and approve your submitted hours.

## Payroll

- **Payment Date:**  
    Salary is usually paid on the 25th of each month.  
    If the 25th falls on a weekend or holiday, payment may be processed on a different day.
- **Example:**  
    On September 25th, you will receive payment for hours worked from August 11th to September 10th.

## Learning Activities

- At the beginning of your employment, you will be assigned learning activities.
- New chapters and materials will be sent to you periodically.

## Goals and Feedback

It makes sense for you to define your own goals after some time in the role, once you have a better understanding of your tasks and responsibilities. It is not mandatory for student assistants but it is definitely encouraged.

## Support

- If you have questions, you can:
    - Email: [DKHR@pandora.net](mailto:DKHR@pandora.net)
    - Ask in the student Teams chat
    - Ask Tomas

---

