---
title: "Introduction"
format: html
---

Glad to have you on the team!

This handbook is here to help you settle in and get up to speed. Inside, you’ll find tips and resources to make your job easier, like:

- **Operational Tasks**: What you’ll be doing day-to-day.
- **Dashboards**: How our dashboards work, with examples, screenshots, and code snippets.
- **Specific Explanations**: Explanations for specific features and measures in our dashboards.
- **Google Cloud Platform (GCP)**: How to use the GCP tools we need.
- **Tabular Editor**: How to handle data models with Tabular Editor.
- **Project Ideas**: Things you can work on, including ongoing projects you might want to pick up.
- **Useful Links**: Handy resources and docs.
- **HR Tips**: How to do things like submit timesheets and manage your schedule.


Check back here whenever you need a reminder or want to learn something new.

Starting a new job can feel overwhelming, but you’ll pick things up quickly. If you get stuck or have questions, just ask Tomas—he’s always happy to help.

All the best, and enjoy your time here!
<div style="margin-top: 2em; font-style: italic;">
Tim
</div>

