---
title: "Useful Links"
format: html
---

A collection of helpful resources and references.

---

> **Internal Portals**
>
> - [PandoraNet SharePoint](https://pandoranet.sharepoint.com/sites/infora)  
>   Internal documentation and resources.
> - [Pandora Digital Wiki](https://pandoradigital.atlassian.net/wiki/home)  
>   Team knowledge base.
> - [Global Assets Home](https://app.exp.pandora.net/p/global-assets/home)  
>   Asset management portal.

---

> **Project Management**
>
> - [Asana Board](https://app.asana.com/0/1200791386796567/board)  
>   Task and project tracking.

---

> **Coding & Data Warehouse**
>
> - [Google Colab](https://colab.research.google.com/)  
>   Cloud-based Python notebooks.
> - [Vertex AI Notebooks](https://console.cloud.google.com/vertex-ai/colab/notebooks?inv=1&invt=AbxSDQ&project=pandora-dashboard-data&activeNb=projects%2Fpandora-dashboard-data%2Flocations%2Feurope-west3%2Frepositories%2Fda582d9c-1852-4bf6-b066-21a610ea0ce5)  
>   Managed Jupyter notebooks.
> - [BigQuery Console](https://console.cloud.google.com/bigquery?project=pandora-dashboard-data&ws=!1m0&pli=1)  
>   Data warehouse management.

---

> **Dashboards & Analytics**
>
> - [Power BI](https://app.powerbi.com/home?experience=power-bi)  
>   Business intelligence dashboards.
> - [LiftLab Dashboard](https://prod.liftlab.com/app/analyze/newroidashboard)  
>   Analytics platform.
> - [Adobe Analytics](https://experience.adobe.com/#/@pandoraas/so:pandor4/analytics/spa/#/workspace/edit/673b14763bcc23475a3e1ab9)  
>   Web analytics.
> - [Google Search Ads](https://searchads.google.com/nav/selectaccount?euid=1283532195&__u=1628308555&authuser=0&f.sid=-8831459738630220990)  
>   Search ads management.

---

> **HR & Scheduling**
>
> - [Learning](https://pandora.eu.crossknowledge.com/interfaces/login.php)  
>   Training portal.
> - [SameSystem](https://in.samesystem.com/c498d25556/schedule/calendar/short?start=2024-11-05)  
>   Scheduling tool.
> - [SuccessFactors Performance Manager](https://performancemanager.successfactors.eu/sf/home?bplte_company=pandoraas&_s.crb=PKCZH0n4YdMPkQsUrl450WoDmhcyaUmXZuVAlR5LGtA%253d)  
>   Performance management.

---

> **Spreadsheets**
>
> - [Google Sheet: Media Spend](https://docs.google.com/spreadsheets/d/1AO5x9HXQ_mzGCo3PGAtDiKgQCET5v3vb7xosHmt1w8o/edit?gid=0#gid=0)  
>   Media spend tracking.
> - [Google Sheet: LL QA](https://docs.google.com/spreadsheets/d/1OOr2oRkGClJGsSQ6pXouvuvFzvSIA4o-W_zYH5vuAe4/edit?gid=0#gid=0)  
>   QA documentation.

---
